add `-i` flag to upload a custom fw to a board
arduino/arduino-fwuploader pull request #117
Opened 2021-09-28 10:38 UTC by umbynos

With this enhancement, a custom local firmware can be uploaded to a board using `-i` or `--input-file` flag:
``` 
./arduino-fwuploader firmware flash -i custom_fw.bin -b arduino:samd:mkr1000 -a /dev/ttyACM0
```

2021-09-28 10:40 UTC, umbynos commented
Needs a rebase after #116 gets merged

2021-09-29 03:32 UTC, per1234 requested changes

2021-09-29 03:32 UTC, per1234 commented on docs/usage.md
> +Or if you want upload a loacal firmware you can use the `-i` or `-input-file` flag followed by the path of that
```suggestion
Or if you want upload a local firmware you can use the `-i` or `--input-file` flag followed by the path of that
```

2021-09-29 08:03 UTC, per1234 approved these changes

2021-09-29 13:30 UTC, ubidefeo approved these changes
tested: works as expected

2021-09-30 10:15 UTC, silvanocerza approved these changes

2021-09-30 10:22 UTC, merged