expand the documentation regarding the certificates flashing
arduino/arduino-fwuploader pull request #129
Opened 2022-02-22 17:35 UTC by umbynos

close #126

2022-02-22 17:43 UTC, facchinm approved these changes

2022-02-23 10:06 UTC, per1234 requested changes

2022-02-23 10:06 UTC, per1234 commented on docs/usage.md
> +Due to a limitation on the handling of certs in the Nina modules, when `certificates flash` command is launched, all the
```suggestion
Due to a limitation on the handling of certs in the NINA modules, when `certificates flash` command is launched, all the
```
I think this "NINA module" term is a bit obscure and potentially confusing, so I think it is best to be as consistent as possible in how it is used.

2022-02-23 10:06 UTC, per1234 commented on docs/usage.md
> +previous certificates are going to be erased. To overcome this it's recommended to upload them all together:
```suggestion
previous certificates are going to be erased. To overcome this it's required to upload them all together:
```
"Recommended" implies this is a best practice, with some other inferior option available. Unless I misunderstand, this is the only way to overcome it, so "required" is the appropriate description.

2022-02-23 10:17 UTC, per1234 approved these changes

2022-02-23 10:18 UTC, merged